# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active-record-streamer 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "active-record-streamer"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kaspernj"]
  s.date = "2015-08-05"
  s.description = "Stream ActiveRecord results"
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "active-record-streamer.gemspec",
    "lib/active-record-streamer.rb",
    "spec/active-record-streamer_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/active-record-streamer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.0"
  s.summary = "Stream ActiveRecord results"

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new("1.2.0")
      s.add_runtime_dependency("baza", [">= 0.0.19"])
      s.add_development_dependency("activerecord", ["= 4.2.1"])
      s.add_development_dependency("mysql2", ["= 0.3.18"])
      s.add_development_dependency("pry", [">= 0"])
      s.add_development_dependency("rspec", ["~> 2.8.0"])
      s.add_development_dependency("rdoc", ["~> 3.12"])
      s.add_development_dependency("bundler", ["~> 1.0"])
      s.add_development_dependency("jeweler", ["~> 2.0.1"])
      s.add_development_dependency("simplecov", [">= 0"])
    else
      s.add_dependency("baza", [">= 0.0.19"])
      s.add_dependency("activerecord", ["= 4.2.1"])
      s.add_dependency("mysql2", ["= 0.3.18"])
      s.add_dependency("pry", [">= 0"])
      s.add_dependency("rspec", ["~> 2.8.0"])
      s.add_dependency("rdoc", ["~> 3.12"])
      s.add_dependency("bundler", ["~> 1.0"])
      s.add_dependency("jeweler", ["~> 2.0.1"])
      s.add_dependency("simplecov", [">= 0"])
    end
  else
    s.add_dependency("baza", [">= 0.0.19"])
    s.add_dependency("activerecord", ["= 4.2.1"])
    s.add_dependency("mysql2", ["= 0.3.18"])
    s.add_dependency("pry", [">= 0"])
    s.add_dependency("rspec", ["~> 2.8.0"])
    s.add_dependency("rdoc", ["~> 3.12"])
    s.add_dependency("bundler", ["~> 1.0"])
    s.add_dependency("jeweler", ["~> 2.0.1"])
    s.add_dependency("simplecov", [">= 0"])
  end
end
